package com.smsapp.audit;

/**
 * Well-known audit action + entity-type identifiers. Keeps these strings out of
 * scattered literals in the services (plan section 7.3).
 */
public final class AuditActions {

    // actions
    public static final String LOGIN_SUCCESS = "LOGIN_SUCCESS";
    public static final String LOGIN_FAILED = "LOGIN_FAILED";
    public static final String TOKEN_REFRESHED = "TOKEN_REFRESHED";
    /** A revoked/expired refresh token was presented again -- treated as a theft signal; the whole chain is revoked. */
    public static final String TOKEN_REUSE_DETECTED = "TOKEN_REUSE_DETECTED";
    public static final String LOGOUT = "LOGOUT";
    public static final String LOGOUT_ALL = "LOGOUT_ALL";
    public static final String STUDENT_CREATED = "STUDENT_CREATED";
    public static final String STUDENT_UPDATED = "STUDENT_UPDATED";
    public static final String STUDENT_STATUS_CHANGED = "STUDENT_STATUS_CHANGED";
    public static final String SECTION_ASSIGNED = "SECTION_ASSIGNED";
    public static final String CLASS_CREATED = "CLASS_CREATED";
    public static final String SECTION_CREATED = "SECTION_CREATED";
    public static final String SUBJECT_CREATED = "SUBJECT_CREATED";
    public static final String CLASS_SUBJECT_ASSIGNED = "CLASS_SUBJECT_ASSIGNED";
    public static final String ATTENDANCE_MARKED = "ATTENDANCE_MARKED";
    public static final String ATTENDANCE_CHANGED = "ATTENDANCE_CHANGED";
    public static final String EXAM_CREATED = "EXAM_CREATED";
    public static final String EXAM_MARK_RECORDED = "EXAM_MARK_RECORDED";
    public static final String EXAM_MARK_CHANGED = "EXAM_MARK_CHANGED";
    public static final String FEE_STRUCTURE_CREATED = "FEE_STRUCTURE_CREATED";
    public static final String INVOICE_CREATED = "INVOICE_CREATED";
    public static final String INVOICE_CHECKOUT_STARTED = "INVOICE_CHECKOUT_STARTED";
    public static final String INVOICE_PAID = "INVOICE_PAID";
    /** DEV-ONLY: an invoice marked paid through the dev-tools simulate endpoint, not a real webhook. */
    public static final String INVOICE_PAID_SIMULATED = "INVOICE_PAID_SIMULATED";
    public static final String FEE_TYPE_CREATED = "FEE_TYPE_CREATED";
    public static final String FEE_DISCOUNT_CREATED = "FEE_DISCOUNT_CREATED";
    public static final String FEE_DISCOUNT_APPLIED = "FEE_DISCOUNT_APPLIED";
    public static final String FEE_LATE_FEE_APPLIED = "FEE_LATE_FEE_APPLIED";
    public static final String FEE_STRUCTURE_STATUS_CHANGED = "FEE_STRUCTURE_STATUS_CHANGED";
    public static final String INVOICES_BULK_ASSIGNED = "INVOICES_BULK_ASSIGNED";
    public static final String FEE_PAYMENT_COLLECTED = "FEE_PAYMENT_COLLECTED";
    public static final String FEE_PAYMENT_REVERSED = "FEE_PAYMENT_REVERSED";
    public static final String ANNOUNCEMENT_CREATED = "ANNOUNCEMENT_CREATED";
    public static final String ANNOUNCEMENT_DELETED = "ANNOUNCEMENT_DELETED";
    public static final String LIBRARY_BOOK_ADDED = "LIBRARY_BOOK_ADDED";
    public static final String LIBRARY_BOOK_ISSUED = "LIBRARY_BOOK_ISSUED";
    public static final String LIBRARY_BOOK_RETURNED = "LIBRARY_BOOK_RETURNED";
    public static final String TRANSPORT_ROUTE_CREATED = "TRANSPORT_ROUTE_CREATED";
    public static final String TRANSPORT_VEHICLE_ADDED = "TRANSPORT_VEHICLE_ADDED";
    public static final String TRANSPORT_ROUTE_ASSIGNED = "TRANSPORT_ROUTE_ASSIGNED";
    public static final String HOSTEL_BLOCK_CREATED = "HOSTEL_BLOCK_CREATED";
    public static final String HOSTEL_ROOM_ADDED = "HOSTEL_ROOM_ADDED";
    public static final String HOSTEL_ROOM_ALLOCATED = "HOSTEL_ROOM_ALLOCATED";
    public static final String STAFF_PROFILE_CREATED = "STAFF_PROFILE_CREATED";
    public static final String STAFF_PROFILE_UPDATED = "STAFF_PROFILE_UPDATED";
    public static final String LEAVE_REQUEST_CREATED = "LEAVE_REQUEST_CREATED";
    public static final String LEAVE_REQUEST_DECIDED = "LEAVE_REQUEST_DECIDED";
    public static final String PAYROLL_RECORD_CREATED = "PAYROLL_RECORD_CREATED";
    public static final String USER_CREATED = "USER_CREATED";
    public static final String USER_UPDATED = "USER_UPDATED";
    public static final String USER_PASSWORD_RESET = "USER_PASSWORD_RESET";
    public static final String USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED";
    public static final String ROLE_CREATED = "ROLE_CREATED";
    public static final String ROLE_PERMISSIONS_UPDATED = "ROLE_PERMISSIONS_UPDATED";
    public static final String PERMISSION_CREATED = "PERMISSION_CREATED";
    public static final String STUDENT_DOCUMENT_UPLOADED = "STUDENT_DOCUMENT_UPLOADED";
    public static final String STUDENT_DOCUMENT_DELETED = "STUDENT_DOCUMENT_DELETED";
    public static final String STUDENT_IDENTIFICATION_ADDED = "STUDENT_IDENTIFICATION_ADDED";
    public static final String STUDENT_IDENTIFICATION_REMOVED = "STUDENT_IDENTIFICATION_REMOVED";
    public static final String STUDENT_PHOTO_UPDATED = "STUDENT_PHOTO_UPDATED";
    public static final String STUDENT_SIBLING_LINKED = "STUDENT_SIBLING_LINKED";
    public static final String ACADEMIC_YEAR_CREATED = "ACADEMIC_YEAR_CREATED";
    public static final String ACADEMIC_YEAR_SET_CURRENT = "ACADEMIC_YEAR_SET_CURRENT";
    public static final String STUDENTS_PROMOTED = "STUDENTS_PROMOTED";
    public static final String ENQUIRY_CREATED = "ENQUIRY_CREATED";
    public static final String ENQUIRY_UPDATED = "ENQUIRY_UPDATED";
    public static final String ENQUIRY_STATUS_CHANGED = "ENQUIRY_STATUS_CHANGED";
    public static final String ENQUIRY_ARCHIVED = "ENQUIRY_ARCHIVED";
    public static final String ENQUIRY_FOLLOWUP_RECORDED = "ENQUIRY_FOLLOWUP_RECORDED";
    public static final String ENQUIRY_CONVERTED = "ENQUIRY_CONVERTED";
    public static final String ENQUIRY_SOURCE_CREATED = "ENQUIRY_SOURCE_CREATED";
    public static final String ENQUIRY_REFERENCE_CREATED = "ENQUIRY_REFERENCE_CREATED";
    public static final String VISITOR_CREATED = "VISITOR_CREATED";
    public static final String VISITOR_UPDATED = "VISITOR_UPDATED";
    public static final String VISITOR_DELETED = "VISITOR_DELETED";
    public static final String VISITOR_ATTACHMENT_UPLOADED = "VISITOR_ATTACHMENT_UPLOADED";
    public static final String VISITOR_ATTACHMENT_REMOVED = "VISITOR_ATTACHMENT_REMOVED";
    public static final String FRONT_OFFICE_PURPOSE_CREATED = "FRONT_OFFICE_PURPOSE_CREATED";
    public static final String PHONE_CALL_CREATED = "PHONE_CALL_CREATED";
    public static final String PHONE_CALL_UPDATED = "PHONE_CALL_UPDATED";
    public static final String PHONE_CALL_DELETED = "PHONE_CALL_DELETED";
    public static final String POSTAL_DISPATCH_CREATED = "POSTAL_DISPATCH_CREATED";
    public static final String POSTAL_DISPATCH_UPDATED = "POSTAL_DISPATCH_UPDATED";
    public static final String POSTAL_DISPATCH_DELETED = "POSTAL_DISPATCH_DELETED";
    public static final String POSTAL_DISPATCH_DOCUMENT_UPLOADED = "POSTAL_DISPATCH_DOCUMENT_UPLOADED";
    public static final String POSTAL_DISPATCH_DOCUMENT_DELETED = "POSTAL_DISPATCH_DOCUMENT_DELETED";
    public static final String POSTAL_RECEIVE_CREATED = "POSTAL_RECEIVE_CREATED";
    public static final String POSTAL_RECEIVE_UPDATED = "POSTAL_RECEIVE_UPDATED";
    public static final String POSTAL_RECEIVE_DELETED = "POSTAL_RECEIVE_DELETED";
    public static final String POSTAL_RECEIVE_DOCUMENT_UPLOADED = "POSTAL_RECEIVE_DOCUMENT_UPLOADED";
    public static final String POSTAL_RECEIVE_DOCUMENT_DELETED = "POSTAL_RECEIVE_DOCUMENT_DELETED";
    public static final String COMPLAINT_CREATED = "COMPLAINT_CREATED";
    public static final String COMPLAINT_UPDATED = "COMPLAINT_UPDATED";
    public static final String COMPLAINT_DELETED = "COMPLAINT_DELETED";
    public static final String COMPLAINT_ATTACHMENT_UPLOADED = "COMPLAINT_ATTACHMENT_UPLOADED";
    public static final String COMPLAINT_ATTACHMENT_REMOVED = "COMPLAINT_ATTACHMENT_REMOVED";
    public static final String COMPLAINT_TYPE_CREATED = "COMPLAINT_TYPE_CREATED";
    public static final String FRONT_OFFICE_SETUP_CREATED = "FRONT_OFFICE_SETUP_CREATED";
    public static final String FRONT_OFFICE_SETUP_UPDATED = "FRONT_OFFICE_SETUP_UPDATED";
    public static final String FRONT_OFFICE_SETUP_DELETED = "FRONT_OFFICE_SETUP_DELETED";
    public static final String FRONT_OFFICE_SETUP_DEACTIVATED = "FRONT_OFFICE_SETUP_DEACTIVATED";
    public static final String ADMISSION_CYCLE_CREATED = "ADMISSION_CYCLE_CREATED";
    public static final String ADMISSION_CYCLE_UPDATED = "ADMISSION_CYCLE_UPDATED";
    public static final String ADMISSION_CYCLE_OPENED = "ADMISSION_CYCLE_OPENED";
    public static final String ADMISSION_CYCLE_CLOSED = "ADMISSION_CYCLE_CLOSED";
    public static final String ADMISSION_APPLICATION_SUBMITTED = "ADMISSION_APPLICATION_SUBMITTED";
    public static final String ADMISSION_APPLICATION_UPDATED = "ADMISSION_APPLICATION_UPDATED";
    public static final String ADMISSION_APPLICATION_STATUS_CHANGED = "ADMISSION_APPLICATION_STATUS_CHANGED";
    public static final String ADMISSION_APPLICATION_DOCUMENT_UPLOADED = "ADMISSION_APPLICATION_DOCUMENT_UPLOADED";
    public static final String ADMISSION_APPLICATION_DOCUMENT_DELETED = "ADMISSION_APPLICATION_DOCUMENT_DELETED";
    public static final String ADMISSION_APPLICATION_CONVERTED = "ADMISSION_APPLICATION_CONVERTED";
    public static final String ADMISSION_ENQUIRY_LINKED = "ADMISSION_ENQUIRY_LINKED";
    public static final String STUDENT_GUARDIAN_LINKED = "STUDENT_GUARDIAN_LINKED";
    public static final String USER_ACTIVATION_ISSUED = "USER_ACTIVATION_ISSUED";
    public static final String USER_ACTIVATED = "USER_ACTIVATED";

    // entity types
    public static final String USER = "USER";
    public static final String REFRESH_TOKEN = "REFRESH_TOKEN";
    public static final String STUDENT = "STUDENT";
    public static final String CLASS = "CLASS";
    public static final String SECTION = "SECTION";
    public static final String SUBJECT = "SUBJECT";
    public static final String CLASS_SUBJECT = "CLASS_SUBJECT";
    public static final String ATTENDANCE_RECORD = "ATTENDANCE_RECORD";
    public static final String EXAM = "EXAM";
    public static final String EXAM_MARK = "EXAM_MARK";
    public static final String FEE_STRUCTURE = "FEE_STRUCTURE";
    public static final String INVOICE = "INVOICE";
    public static final String FEE_TYPE = "FEE_TYPE";
    public static final String FEE_DISCOUNT = "FEE_DISCOUNT";
    public static final String FEE_PAYMENT = "FEE_PAYMENT";
    public static final String ANNOUNCEMENT = "ANNOUNCEMENT";
    public static final String LIBRARY_BOOK = "LIBRARY_BOOK";
    public static final String BOOK_LOAN = "BOOK_LOAN";
    public static final String TRANSPORT_ROUTE = "TRANSPORT_ROUTE";
    public static final String TRANSPORT_VEHICLE = "TRANSPORT_VEHICLE";
    public static final String HOSTEL_BLOCK = "HOSTEL_BLOCK";
    public static final String HOSTEL_ROOM = "HOSTEL_ROOM";
    public static final String STAFF_PROFILE = "STAFF_PROFILE";
    public static final String LEAVE_REQUEST = "LEAVE_REQUEST";
    public static final String PAYROLL_RECORD = "PAYROLL_RECORD";
    public static final String ROLE = "ROLE";
    public static final String PERMISSION = "PERMISSION";
    public static final String ACADEMIC_YEAR = "ACADEMIC_YEAR";
    public static final String ENQUIRY = "ENQUIRY";
    public static final String ENQUIRY_FOLLOW_UP = "ENQUIRY_FOLLOW_UP";
    public static final String ENQUIRY_SOURCE = "ENQUIRY_SOURCE";
    public static final String ENQUIRY_REFERENCE = "ENQUIRY_REFERENCE";
    public static final String VISITOR = "VISITOR";
    public static final String FRONT_OFFICE_PURPOSE = "FRONT_OFFICE_PURPOSE";
    public static final String PHONE_CALL = "PHONE_CALL";
    public static final String POSTAL_DISPATCH = "POSTAL_DISPATCH";
    public static final String POSTAL_RECEIVE = "POSTAL_RECEIVE";
    public static final String COMPLAINT = "COMPLAINT";
    public static final String COMPLAINT_TYPE = "COMPLAINT_TYPE";
    public static final String FRONT_OFFICE_SETUP_ITEM = "FRONT_OFFICE_SETUP_ITEM";
    public static final String STUDENT_DOCUMENT = "STUDENT_DOCUMENT";
    public static final String STUDENT_IDENTIFICATION = "STUDENT_IDENTIFICATION";
    public static final String ADMISSION_CYCLE = "ADMISSION_CYCLE";
    public static final String ADMISSION_APPLICATION = "ADMISSION_APPLICATION";
    public static final String ADMISSION_APPLICATION_DOCUMENT = "ADMISSION_APPLICATION_DOCUMENT";
    public static final String USER_ACTIVATION_TOKEN = "USER_ACTIVATION_TOKEN";

    private AuditActions() {
    }
}
